### ISSUE TITLE
security and admin users set up by default?

### ISSUE THREAD

**Issue by aioue** [ohtomi/ansible-role-jenkins2#1]
Is security enabled and the admin user and pass set up using this role?

**Comment by ohtomi** [comment]
What does "security" means?
This role doesn't support the admin user and password. I think there is no way to configure the admin user and password using shell scripts.

**Comment by aioue** [comment]
'Manage Jenkins' -> 'configure global security' 

![image](https://user-images.githubusercontent.com/1254905/27425626-ec8b5eea-5730-11e7-8bdb-9372f6f81495.png)

Ok thank you. I will try to find another way of creating users.
